### PR TITLE
Update dependencies and fix grand exchange test

### PR DESCRIPTION
**Pull request by QuentinGibson**
Added some small commits that does what the title says, adds yarn.lock file, and updates the .gitignore file using gitignore.io

### CODE REVIEW

**Comment by Joshua-F** [comment]
Did they change how the API works for GE?

**Comment by QuentinGibson** [comment]
no not at all but "0" was making it fail even though the examples work.

**Comment by Joshua-F** [comment]
I'll merge this in but I'm not going to bump the version for it. Thanks :)

**Comment by Joshua-F** [comment]
Side note: You should add the email you commit with to your Github account so that your commits link back to your actual account.

**Comment by QuentinGibson** [comment]
Will look into that. thank you.

**Pull request merged**
