### PR TITLE
Add Invention

### PR DESCRIPTION
**Pull request by Swinkid**

### CODE REVIEW

**Comment by Joshua-F** [comment]
Looks good, going to go ahead and close #4 without merge and I'll add a few other things then bump the version myself. I'll release a new version here pretty soon.

**Comment by Swinkid** [comment]
Thanks buddy, Needed this for some project im doing, sooner the newer version the better :)

**Comment by Joshua-F** [comment]
1.0.7 has been release tagged and release :)

**Comment by Swinkid** [comment]
Updated my project, thanks for this swiftness!

**Pull request merged**
